config/routes.rb
Rails.application.routes.draw do
  
  # get 'restaurants/new', to: 'restaurants#new', as: :new_restaurant # render the form to create the restaurant

  # post 'restaurants', to: 'restaurants#create' # create the restaurant on the DB -> when the form is submited

  # get 'restaurants/:id/edit', to: 'restaurants#edit', as: :edit_restaurant # render the form to edit the restaurant

  # patch 'restaurants/:id', to: 'restaurants#update' # edit the restaurant on the DB -> when the form is submited

  # get 'restaurants', to: 'restaurants#index' # list restaurants

  # get 'restaurants/:id', to: 'restaurants#show', as: :restaurant # show restaurants with a new name for the link

  # delete 'restaurants/:id', to: 'restaurants#destroy' 

  # all of the previous routes are automacally generated by the next line 
  resources :restaurants

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy] 
  # setting the restaurant like line 10, 30, 35, 44

  def index
  	@restaurants = Restaurant.all
  end

  def show
  	# @restaurant = Restaurant.find(params[:id])
  end

  def new
  	@restaurant = Restaurant.new
  end

  def create
  	# Create the restaurant using params into the DB
  	# 
  	# Restaurant.create(name: params[:name], address: params[:address], stars: params[:stars])
  	# instead of doing this we create a restaurant hash inside params hash and filter the attributes
  	# using a private method like restaurant_params
  	Restaurant.create(restaurants_params)

  	redirect_to restaurants_path
  end


  def edit
  	# @restaurant = Restaurant.find(params[:id])
  end

  def update
  	# get it again from DB
  	# @restaurant = Restaurant.find(params[:id])
  	# Update with the new params
  	@restaurant.update(restaurants_params)

  	redirect_to restaurants_path
  end

  def destroy
  	# get it from the DB
  	# @restaurant = Restaurant.find(params[:id])

  	# Destroy
  	@restaurant.destroy

  	# Redirect the user to the list
  	redirect_to restaurants_path	
  end

  private

  def set_restaurant
  	@restaurant = Restaurant.find(params[:id]) 
  end

  def restaurants_params
  	params.require(:restaurant).permit(:name, :address, :stars)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RestaurantsManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :address %>
  <%= f.text_field :address %>

  <%= f.label :stars %>
  <%= f.number_field :stars %>

  <%= f.submit %>
<% end %>


<!-- HTML RAW code for creating restaurant -->
<!-- <form action="/restaurants" method="post">
	<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
	<input type="text" name="restaurant[name]" value="" placeholder="Name">
	<input type="text" name="restaurant[address]" value="" placeholder="Address">
	<input type="number" name="restaurant[stars]" value="" placeholder="Stars">
	<input type="submit" >
</form> -->

<!-- HTML RAW code for edit restaurant -->
<!-- <form action="/restaurants/<%= @restaurant.id %>" method="post">
	<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
	<%= hidden_field_tag :_method, 'patch' %>
	<input type="text" name="restaurant[name]" value="<%= @restaurant.name %>" placeholder="Name">
	<input type="text" name="restaurant[address]" value="<%= @restaurant.address %>" placeholder="Address">
	<input type="number" name="restaurant[stars]" value="<%= @restaurant.stars %>" placeholder="Stars">
	<input type="submit" >
</form> -->

app/views/restaurants/edit.html.erb
<h1>Edit Restaurant</h1>

<%= render 'form' %>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>

<p><%= link_to 'New Restaurant', new_restaurant_path %></p>
<ul>
<% @restaurants.each do |r| %>
	<li><%= link_to r.name, restaurant_path(id: r.id) %></li>
<% end %>
</ul>

app/views/restaurants/new.html.erb
<h1>Create New Restaurant</h1>


<%= render 'form' %>

app/views/restaurants/show.html.erb
<h1>Restaurant <%= @restaurant.name %></h1>

<p>Address: <%= @restaurant.address %></p>

<p>Stars: <%= @restaurant.stars %></p>

<%= link_to 'Edit', edit_restaurant_path(id: @restaurant.id) %>
<%= link_to 'Delete', restaurant_path(id: @restaurant.id), method: :delete %>
<%= link_to 'List All', restaurants_path %>